//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommercial
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment_Product()
        {
            this.Comment_Image = new HashSet<Comment_Image>();
        }
    
        public int Comment_Id { get; set; }
        public string Comment_Content { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ID_Customer { get; set; }
        public Nullable<int> Rate_point { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_Image> Comment_Image { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
