//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommercial
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_Image
    {
        public int Image_Id { get; set; }
        public Nullable<int> ID_Comment { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Comment_Product Comment_Product { get; set; }
    }
}
