//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommercial
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatHang
    {
        public int IdMatHang { get; set; }
        public string TenMatHang { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<System.DateTime> CreatetionTime { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
