//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommercial
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public int OrderDetails_Id { get; set; }
        public int ID_Product { get; set; }
        public int ID_Order { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Discount { get; set; }
        public string Total_Price { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
